site_name: Git Basic
repo_url: https://github.com/WilliamCutrim/git_in_a_nutshell
repo_name: WilliamCutrim/git_in_a_nutshell

theme:
  name: material

  palette:
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Modo noturno

plugins:
- search
- mkdocs_quiz

nav:
  - Basic Commands: index.md
  - Gitflow: git_flow.md
  - Create Branch: create_branch.md
  - Git Pull and Git Push: pull_push.md
  - Gitcheckout Merge and rebase: gitcheckout.md
  - Conflicts: conflict.md
  - Pull Request: pull_request.md
  - Good practices: good_pratices.md
  - Gitignore: gitignore.md
  - Quiz: quiz.md
  - References: references.md