site_name: Git Basic

theme:
 name: material

plugins:
- search
- mkdocs_quiz

nav:
  - Basic Commands: index.md
  - Gitflow: git_flow.md
  - Create Branch: create_branch.md
  - Git Pull and Git Push: pull_push.md
  - Gitcheckout Merge and rebase: gitcheckout.md
  - Conflicts: conflict.md
  - Pull Request: pull_request.md
  - Good practices: good_pratices.md
  - Gitignore: gitignore.md
  - Quiz: quiz.md
  - References: references.md